x-build: &x-build
  context: .
  cache_from:
    - primo-explore-central-package
    - quay.io/nyulibraries/primo-explore-central-package
    - quay.io/nyulibraries/primo-explore-central-package:$BRANCH_NO_SLASH

x-environment: &x-environment
  PROXY_SERVER: http://bobcatdev.library.nyu.edu:80
  VIEW: CENTRAL_PACKAGE
  NODE_ENV: ${NODE_ENV-development}

x-defaults: &x-defaults
  build:
    <<: *x-build
  image: primo-explore-central-package
  environment:
    <<: *x-environment
  volumes:
    - ./:/app/primo-explore/custom/CENTRAL_PACKAGE

version: '3.7'
services:
  web:
    <<: *x-defaults
    ports:
    - 8004:8004
    - 3001:3001
    command: yarn start:dev --host 0.0.0.0
  create-package:
    <<: *x-defaults
    environment:
      <<: *x-environment
      NODE_ENV: ${NODE_ENV-staging}
      PACK: 'true'
    command: yarn webpack
    depends_on:
      - web
  e2e:
    image: primo-explore-cypress
    build:
      <<: *x-build
      args: {}
      dockerfile: cypress/Dockerfile
    command: yarn cypress run # --browser chrome
    depends_on:
      - web
    environment:
      <<: *x-environment
      NODE_ENV: test
      CYPRESS_BASE_URL: http://web:8004/primo-explore/search
    volumes:
      - ./cypress/:/app/cypress