docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:18.06.1-dc-1.23.2-0
  working_directory: ~/app

build_docker: &build_docker
  run:
    name: Build Docker
    command: |
      docker-compose build web e2e

auth_quay: &auth_quay
  run:
    name: Authenticate Quay
    command: |
      docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io

pull_docker: &pull_docker
  run:
    name: Pull Docker
    command: |
      script/pull_docker.sh

push_docker: &push_docker
  run:
    name: Push Docker
    command: |
      script/push_docker.sh

test: &test
  run:
    name: Run E2E Tests
    command: |
      docker-compose run e2e cypress run --reporter junit --reporter-options "mochaFile=test-results/test-output.xml"

store-test: &store-test
  run:
    name: Copy testing store_artifacts
    when: always
    command: |
      docker cp "$(docker ps -q -a -l -f name=e2e)":/app/cypress cypress
      docker cp "$(docker ps -q -a -l -f name=e2e)":/app/test-results test-results


version: 2
jobs:
  build-and-test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *auth_quay
      - <<: *pull_docker
      - <<: *build_docker
      - <<: *test
      - <<: *store-test
      - <<: *push_docker
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
